"""AI Service domain exceptions package."""

from .ai_exceptions import (
    AIServiceException,
    ConversationNotFoundError,
    KnowledgeBaseError,
    ModelNotAvailableError,
    InvalidPromptError,
    TokenLimitExceededError,
    EmbeddingError,
    VectorStoreError,
    ConversationLimitExceededError,
    InvalidModelConfigurationError,
    AIProviderError,
    ModelNotFoundError,
    RateLimitError,
    InvalidInputError,
    CacheError,
    PredictionError,
    PredictionNotFoundError,
    InvalidPredictionDataError,
    PredictionModelError,
    InsufficientDataError,
    AlertError,
    AlertNotFoundError,
    InvalidAlertDataError,
    AlertPermissionError,
    AlertStatusError,
)

__all__ = [
    "AIServiceException",
    "ConversationNotFoundError",
    "KnowledgeBaseError",
    "ModelNotAvailableError",
    "InvalidPromptError",
    "TokenLimitExceededError",
    "EmbeddingError",
    "VectorStoreError",
    "ConversationLimitExceededError",
    "InvalidModelConfigurationError",
    "AIProviderError",
    "ModelNotFoundError",
    "RateLimitError",
    "InvalidInputError",
    "CacheError",
    "PredictionError",
    "PredictionNotFoundError",
    "InvalidPredictionDataError",
    "PredictionModelError",
    "InsufficientDataError",
    "AlertError",
    "AlertNotFoundError",
    "InvalidAlertDataError",
    "AlertPermissionError",
    "AlertStatusError",
]
